# Generated by Django 2.1.15 on 2021-05-18 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communitymanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='abonnements',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='communitymanager.Communaute'),
        ),
    ]
