# Generated by Django 2.1.15 on 2021-05-18 10:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communitymanager', '0002_user_abonnements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='abonnements',
        ),
        migrations.AlterField(
            model_name='communaute',
            name='abonnes',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
