# Generated by Django 2.1.15 on 2021-05-19 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communitymanager', '0003_auto_20210518_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='communaute',
            name='statut',
            field=models.BooleanField(default=False),
        ),
    ]
