# Generated by Django 2.1.15 on 2021-05-20 09:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communitymanager', '0006_auto_20210520_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communaute',
            name='abonnes',
            field=models.ManyToManyField(blank=True, related_name='abonnés', to=settings.AUTH_USER_MODEL),
        ),
    ]
