# Generated by Django 2.1.15 on 2021-05-21 15:13

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communitymanager', '0007_auto_20210520_0937'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date du commentaire')),
                ('evenementiel', models.BooleanField(default=False)),
                ('date_evenement', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date de l'évenement")),
                ('auteur', models.ForeignKey(on_delete='models.CASCADE', to=settings.AUTH_USER_MODEL)),
                ('communaute', models.ForeignKey(on_delete='models.CASCADE', to='communitymanager.Communaute')),
            ],
        ),
        migrations.CreateModel(
            name='Priorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labels', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='priorite',
            field=models.ForeignKey(on_delete='models.CASCADE', to='communitymanager.Priorite'),
        ),
    ]
