# Generated by Django 2.1.15 on 2021-05-22 12:10

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communitymanager', '0009_post_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date du commentaire')),
                ('contenu', models.CharField(max_length=250)),
                ('auteur', models.ForeignKey(on_delete='models.CASCADE', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete='models.CASCADE', to='communitymanager.Post')),
            ],
        ),
    ]
