# Generated by Django 2.1.15 on 2021-05-22 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communitymanager', '0013_auto_20210522_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='evenementiel',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
