# Generated by Django 2.1.15 on 2021-05-22 16:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('communitymanager', '0014_auto_20210522_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date du Post'),
        ),
    ]
