# Generated by Django 2.1.15 on 2021-05-22 16:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('communitymanager', '0015_auto_20210522_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaire',
            name='date_creation',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 22, 16, 32, 29, 811067, tzinfo=utc), verbose_name='Date du commentaire'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_creation',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 22, 16, 32, 29, 810540, tzinfo=utc), verbose_name='Date du Post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_evenement',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 22, 16, 32, 29, 810579, tzinfo=utc), verbose_name="Date de l'évenement"),
        ),
    ]
