# Generated by Django 2.1.15 on 2021-05-23 15:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('communitymanager', '0016_auto_20210522_1632'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['date_creation']},
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date du commentaire'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date du post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_evenement',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date de l'évenement"),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(max_length=25000),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=250),
        ),
    ]
