# Generated by Django 2.1.15 on 2021-05-24 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communitymanager', '0019_auto_20210524_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_evenement',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name="Date de l'évenement"),
        ),
    ]
