# Generated by Django 2.1.15 on 2021-05-25 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communitymanager', '0020_auto_20210524_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date_evenement',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date de l'évenement"),
        ),
    ]
