# Generated by Django 2.1.15 on 2021-05-25 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communitymanager', '0027_auto_20210525_1038'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentaire',
            options={'ordering': ['date_creation']},
        ),
        migrations.AlterField(
            model_name='post',
            name='date_evenement',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date de l'évenement"),
        ),
    ]
