# Generated by Django 2.1.15 on 2021-05-26 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communitymanager', '0029_auto_20210526_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communaute',
            name='statut',
        ),
    ]
