# Generated by Django 2.2 on 2021-05-31 09:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communitymanager', '0030_remove_communaute_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communaute',
            name='abonnes',
            field=models.ManyToManyField(blank=True, related_name='abonnements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='auteur',
            field=models.ForeignKey(on_delete='models.CASCADE', related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
