# Generated by Django 2.2 on 2021-05-31 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communitymanager', '0030_remove_communaute_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='priorite',
            name='rang',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
