# Generated by Django 2.2 on 2021-05-29 16:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communitymanager', '0030_remove_communaute_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='communaute',
            name='createur',
            field=models.ForeignKey(default=None, on_delete='models.CASCADE', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
