# Generated by Django 2.2 on 2021-06-01 16:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communitymanager', '0031_priorite_rang'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='lecteurs',
            field=models.ManyToManyField(blank=True, related_name='lecteurs', to=settings.AUTH_USER_MODEL),
        ),
    ]
