# Generated by Django 2.2 on 2021-05-29 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communitymanager', '0031_communaute_createur'),
    ]

    operations = [
        migrations.AddField(
            model_name='communaute',
            name='description',
            field=models.CharField(default=None, max_length=2500),
            preserve_default=False,
        ),
    ]
