# Generated by Django 2.2 on 2021-05-30 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communitymanager', '0039_auto_20210530_1330'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-collant', '-date_creation']},
        ),
    ]
