# Generated by Django 2.2 on 2021-05-30 17:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communitymanager', '0042_auto_20210530_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaire',
            name='auteur',
            field=models.ForeignKey(on_delete='models.ON_CASCADE', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='post',
            field=models.ForeignKey(on_delete='models.ON_CASCADE', to='communitymanager.Post'),
        ),
        migrations.AlterField(
            model_name='communaute',
            name='createur',
            field=models.ForeignKey(on_delete='models.ON_CASCADE', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='auteur',
            field=models.ForeignKey(on_delete='models.ON_CASCADE', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='communaute',
            field=models.ForeignKey(default=None, on_delete='models.CASCADE', to='communitymanager.Communaute'),
        ),
        migrations.AlterField(
            model_name='post',
            name='priorite',
            field=models.ForeignKey(on_delete='models.CASCADE', to='communitymanager.Priorite'),
        ),
    ]
