# Generated by Django 2.2 on 2021-05-31 09:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communitymanager', '0047_auto_20210530_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communaute',
            name='abonnes',
            field=models.ManyToManyField(blank=True, related_name='abonnes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='communaute',
            field=models.ForeignKey(on_delete='models.DO_NOTHING', to='communitymanager.Communaute'),
        ),
    ]
