# Generated by Django 2.2 on 2021-05-31 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communitymanager', '0048_auto_20210531_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaire',
            name='auteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communitymanager.Post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='auteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='communaute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communitymanager.Communaute'),
        ),
        migrations.AlterField(
            model_name='post',
            name='priorite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='communitymanager.Priorite'),
        ),
    ]
