# Generated by Django 2.2 on 2021-05-31 10:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communitymanager', '0049_auto_20210531_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='communaute',
            name='list_bannis',
            field=models.ManyToManyField(blank=True, related_name='bannis', to=settings.AUTH_USER_MODEL),
        ),
    ]
