# Generated by Django 2.2 on 2021-05-31 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communitymanager', '0050_communaute_list_bannis'),
    ]

    operations = [
        migrations.AddField(
            model_name='communaute',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
