# Generated by Django 2.2 on 2021-05-31 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communitymanager', '0051_communaute_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='communaute',
            name='invisible',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='communaute',
            name='visible',
            field=models.BooleanField(default=False),
        ),
    ]
