# Generated by Django 2.2 on 2021-05-31 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communitymanager', '0052_auto_20210531_1537'),
    ]

    operations = [
        migrations.RenameField(
            model_name='communaute',
            old_name='invisible',
            new_name='ferme_invisible',
        ),
        migrations.RenameField(
            model_name='communaute',
            old_name='visible',
            new_name='ferme_visible',
        ),
    ]
