# Generated by Django 2.2 on 2021-05-31 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communitymanager', '0053_auto_20210531_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communaute',
            name='ferme_visible',
        ),
    ]
