# Generated by Django 2.2 on 2021-06-01 07:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communitymanager', '0055_post_avertissement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communaute',
            name='abonnes',
            field=models.ManyToManyField(blank=True, related_name='abonnements', to=settings.AUTH_USER_MODEL),
        ),
    ]
