# Generated by Django 2.2 on 2021-06-02 09:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communitymanager', '0057_auto_20210602_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communaute',
            name='abonnes',
            field=models.ManyToManyField(blank=True, related_name='abonnements', to=settings.AUTH_USER_MODEL),
        ),
    ]
