# Generated by Django 2.2 on 2021-06-02 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communitymanager', '0033_post_likes'),
        ('communitymanager', '0058_auto_20210602_1117'),
    ]

    operations = [
    ]
