# Generated by Django 2.2 on 2021-06-06 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communitymanager', '0060_communaute_list_cms'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-avertissement', '-collant', '-date_creation']},
        ),
    ]
